# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:latest
WORKDIR /usr/dev/frontend/

#install deps
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

#Copy source code
COPY . .

# run the app
EXPOSE 5173/tcp
ENTRYPOINT [ "bun", "run", "dev" ]
